Faculty Survey 2015
========================================================



```{r}

f <- read.csv("Faculty Survey 2014 (Responses).csv",header=T)

#cleaning
f$Timestamp <- as.Date(f$Timestamp,"%m/%d/%Y")
f = f[grep("(2015)|(2016)",f$Timestamp),]
levs = c("Very Dissatisfied","Dissatisfied","Uncertain","Satisfied","Very Satisfied")
for (i in 2:15) f[,i] <- factor(f[,i],levels=levs)
f$Academic.rank.<- factor(f$Academic.rank.,levels=c("Lecturer","Assistant Professor","Associate Professor","Professor"))
#*********

library(likert)
lik <- likert(f[,2:15])
likert.heat.plot(lik,centered=F,ordered=T,plot.percent.neutral=F)+ggtitle("Faculty Survey during 2015")

f1 <- f[,2:8]
f2 <- f[,9:15]
lik1 <- likert(f1,grouping=f[,18])
lik2 <- likert(f2,grouping=f[,18])
jpeg(filename="faculty survey 2015/lbp1.jpg",width=600,height=800)
likert.bar.plot(lik1,centered=F,ordered=T,plot.percent.neutral=F)+ggtitle("Faculty Survey during 2015")
dev.off()

jpeg(filename="faculty survey 2015/lbp2.jpg",width=600,height=800)
likert.bar.plot(lik2,centered=F,ordered=T,plot.percent.neutral=F)+ggtitle("Faculty Survey during 2015")
dev.off()
#************
#tabling
#tt <- t(f[2:15]);a <- melt(tt); b=table(a$X2,a$value)
#library(vcd);library(gmodels)
#tab=CrossTable(a$X1,a$value);




```


```{r}
# Core wrapping function
wrap.it <- function(x, len)
{ 
  sapply(x, function(y) paste(strwrap(y, len), 
                              collapse = "\n"), 
         USE.NAMES = FALSE)
}


# Call this function with a list or vector
wrap.labels <- function(x, len)
{
  if (is.list(x))
  {
    lapply(x, wrap.it, len)
  } else {
    wrap.it(x, len)
  }
}
```

BootStrapping with Faculty Survey

```{r}
sampleMean <- function (population, indicator,year)
{
  population.mean= mean(population,na.rm=T)
B=1000
n= length(population)
boot.samples = matrix(sample(population, size=B*n, replace=T),nrow=B,ncol=n)

boot.statistics = apply(boot.samples,1,mean,na.rm=T)
hist(boot.statistics,100, main=paste("Histogram of boot statistic of ",indicator,"Year:",year),xlim=c(2.6,4.4))
sample.se = sd(boot.statistics,na.rm=T)

me = ceiling(10*2*sample.se)/10

print (round(population.mean,1)+ c(1,-1)*me)
}
f <- read.csv("c:/r/Rspace/faculty survey 2015/Faculty Survey 2014 (Responses).csv",header=T,colClasses="character")

#cleaning
f$Timestamp <- as.Date(f$Timestamp,"%m/%d/%Y")
ft = f

f=f[,2:15]
f[f=="Very Satisfied"] <- 5
f[f=="Satisfied"] <- 4
f[f=="Uncertain"] <- 3
f[f=="Dissatisfied"] <- 2
f[f=="Very Dissatisfied"] <- 1

f1 = f[grep("(2013)",ft$Timestamp),]
f2 = f[grep("(2015)|(2016)",ft$Timestamp),]
#f1=f1[,2:15];f2=f2[,2:15]
par(mfrow=c(4,1))
for ( i in names(f)){
  sampleMean(as.integer(f1[,names(f1)==i]),i,2013)
  sampleMean(as.integer(f2[,names(f2)==i]),i,2015)
  }

```

Running Classing t-test on selective questionnaire

```{r}
t.test(f1$Salary.and.compensation.package.,f2$Salary.and.compensation.package.,na.action=T
       )


```
